services:
  database:
    image: mysql:8.0
    container_name: mysql
    stdin_open: true
    restart: always
    environment:
      MYSQL_DATABASE: leboncoin
      MYSQL_ROOT_PASSWORD: root
    ports:
        - "3307:3306"
    volumes:
        - ./data:/var/lib/mysql
        - ./conf:/etc/mysql/conf.d
        - ./logs:/logs
  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: database
    ports:
      - 8080:80
  server:
    build: 
        context: ./server
    depends_on:
     - database
    environment:
      MYSQL_HOST_IP: database
      MYSQL_USER: root
      MYSQL_DATABASE: leboncoin
      MYSQL_PASSWORD: root
    ports:
      - "5000:5000"
    volumes:
      - ./server:/server
  client:
    container_name: client
    build: 
      context: ./client
    ports:
      - "3000:80"
    volumes:
      - ./src:/src
volumes:
  mysql:
    driver: local

    